apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dremio-master
spec:
  serviceName: "dremio-cluster-pod"
  replicas: 1
  selector:
    matchLabels:
      app: dremio-coordinator
  template:
    metadata:
      labels:
        app: dremio-coordinator
        role: dremio-cluster-pod
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - dremio-master
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 5
      containers:
      - name: dremio-master-coordinator
        image: dremio/dremio-oss:4.1.7
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 8000M
            cpu: 2
        volumeMounts:
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        - name: dremio-config
          mountPath: /opt/dremio/conf
        env:
        - name: DREMIO_MAX_HEAP_MEMORY_SIZE_MB
          value: "4096"
        - name: DREMIO_MAX_DIRECT_MEMORY_SIZE_MB
          value: "2000"
        - name: DREMIO_JAVA_EXTRA_OPTS
          value: >-
            -Dzookeeper=zk-hs:2181
            -Dservices.coordinator.master.embedded-zookeeper.enabled=false
            -Dservices.executor.enabled=false
        command: ["/opt/dremio/bin/dremio"]
        args:
        - "start-fg"
        ports:
        - containerPort: 9047
          name: web
        - containerPort: 31010
          name: client
        - containerPort: 45678
          name: server
        readinessProbe:
          httpGet:
            path: /
            port: 9047
          initialDelaySeconds: 5
          periodSeconds: 5
      initContainers:
      - name: chown-data-directory
        image: dremio/dremio-oss:4.1.7
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        command: ["chown"]
        args:
        - "dremio:dremio"
        - "/opt/dremio/data"
      - name: upgrade-task
        image: dremio/dremio-oss:4.1.7
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        command: ["/opt/dremio/bin/dremio-admin"]
        args:
        - "upgrade"
      volumes:
      - name: dremio-config
        configMap:
          name: dremio-config
  volumeClaimTemplates:
  - metadata:
      name: dremio-master-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
