apiVersion: v1
kind: Service
metadata:
  name: dremio-client
  labels:
    app: dremio-client
spec:
  ports:
  - port: 31010
    targetPort: 31010
    name: client
  - port: 9047
    targetPort: 9047
    name: web
  selector:
    app: dremio-coordinator
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: dremio-cluster-pod
spec:
  ports:
  - port: 9999
  clusterIP: None
  selector:
    role: dremio-cluster-pod
